kanta_str = input("Anna suorakulmion kannan pituus")
korkeus_str = input("Anna suorakulmion korkeus")
kanta = float(kanta_str)
korkeus = float(korkeus_str)
print("Suorakulmion piiri on " + str(kanta*2 + korkeus*2) + " ja pinta-ala on " + str(kanta*korkeus))